import turtle
t=turtle.Turtle()
t.shape("turtle")
#size=int(intput="집의 크기는 얼마로 할까여?"))
size=int(turtle.textinput("입력하기 이거 제목임","집의 크기는 얼마로 할까요?"))
t.forward(size)
t.right(90)
t.forward(size);t.right(90);t.forward(size);t.right(90);t.forward(size)
t.right(90)
t.forward(size);t.left(120);t.forward(size);t.left(1201);t.forward(size)
t.left(120)
turtle.exitonclick()